language: node_js
node_js:
    - 12.18
services:
    - postgresql
before_script:
    - psql -c 'create database taskb;' -U postgres
scripts:
    - npm run test
    - npm install -g serverless
    - npm run deploy
